name: documentation

# on: [push, pull_request, workflow_dispatch]
on: 
  # workflow_dispatch:
  # release:
  #   types: [published]
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme myst_parser sphinx-copybutton sphinx-multiversion
      - name: install requirements with no dependencies
        # run: |
        #   pip install -r requirements.txt --no-dependencies
      - name: Sphinx build
        run: |
          sphinx-build docs/source _build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
